# Generated by Django 2.0 on 2018-01-08 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tdrivers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apName', models.CharField(max_length=100)),
                ('apCity', models.CharField(max_length=100)),
                ('apShortName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cFirstName', models.CharField(max_length=200)),
                ('cLastName', models.CharField(max_length=200)),
                ('cDocNumber', models.CharField(max_length=50)),
                ('cDOB', models.DateField(blank=True, null=True)),
                ('cEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('cPhone', models.CharField(blank=True, max_length=20, null=True)),
                ('cTlgMsg', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flNumber', models.CharField(max_length=50)),
                ('flDate', models.DateTimeField()),
                ('flDestOther', models.CharField(max_length=1000)),
                ('isAccept', models.BooleanField(default=False)),
                ('accDate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('accpDriver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdrivers.tDriver')),
                ('fAirport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Airports')),
                ('fClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dName', models.CharField(max_length=100)),
                ('dCity', models.CharField(max_length=100)),
                ('dAddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gType', models.CharField(max_length=2)),
                ('gTypeDescr', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='clientflight',
            name='flDestination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Destination'),
        ),
        migrations.AddField(
            model_name='clientflight',
            name='isAccepted',
            field=models.BooleanField(default=False, blank=True),
        ),
        migrations.AddField(
            model_name='clientflight',
            name='accDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='clientflight',
            name='accpDriver',
            field=models.ForeignKey(blank=True, null=True,on_delete=django.db.models.deletion.CASCADE, to='tdrivers.tDriver'),
        ),
        migrations.AddField(
            model_name='client',
            name='cGender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Gender'),
        ),
        migrations.AddField(
            model_name='client',
            name='iUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
