# Generated by Django 2.0 on 2018-01-08 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientflight',
            name='isAccept',
        ),
        migrations.AlterField(
            model_name='clientflight',
            name='accpDriver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdrivers.tDriver'),
        ),
    ]
